version: "3"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - app-network
    restart: always

  frontend:
    build: .
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: jonas1385
      POSTGRES_DB: primeiraapi
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always

  zabbix-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: zabbixpass
      POSTGRES_USER: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
      POSTGRES_DB: zabbix
    depends_on:
      - zabbix-db
    ports:
      - "10051:10051"
    networks:
      - app-network
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
      POSTGRES_DB: zabbix
    depends_on:
      - zabbix-server
    ports:
      - "8081:8080"
    networks:
      - app-network
    restart: always

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: zabbix-agent
    depends_on:
      - zabbix-server
    ports:
      - "10050:10050"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  zabbix-db-data:
